import { DocsLayout } from "./DocsLayout";

export default function License() {
  return (
    <DocsLayout>
      <article className="prose prose-slate dark:prose-invert max-w-none">
        <h1 id="license">License</h1>
        
        <p className="lead">
          Go Bootstrapper is open source software licensed under the MIT License.
        </p>

        <h2 id="mit-license">MIT License</h2>

        <pre className="bg-muted p-6 rounded-lg border border-border overflow-x-auto">
          <code className="text-sm">{`MIT License

Copyright (c) 2025 Saurav Upadhyay

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`}</code>
        </pre>

        <h2 id="what-this-means">What This Means</h2>

        <p>The MIT License is a permissive free software license. You are free to:</p>

        <ul>
          <li>✅ Use Go Bootstrapper commercially</li>
          <li>✅ Modify the source code</li>
          <li>✅ Distribute copies or modifications</li>
          <li>✅ Use it privately</li>
          <li>✅ Sublicense the software</li>
        </ul>

        <p>The only requirements are:</p>

        <ul>
          <li>📄 Include the original copyright notice</li>
          <li>📄 Include the license text</li>
        </ul>

        <h2 id="no-warranty">No Warranty</h2>

        <p>
          Go Bootstrapper is provided "as is", without warranty of any kind. The authors
          are not liable for any claims, damages, or other liability arising from the use
          of this software.
        </p>

        <h2 id="generated-projects">Generated Projects</h2>

        <p>
          Projects generated by Go Bootstrapper are <strong>yours</strong>. You own the
          copyright to the generated code and can license it however you choose.
        </p>

        <h2 id="questions">Questions?</h2>

        <p>
          If you have questions about licensing, feel free to{" "}
          <a href="https://github.com/upsaurav12/bootstrap/issues" target="_blank" rel="noreferrer">
            open an issue on GitHub
          </a>.
        </p>
      </article>
    </DocsLayout>
  );
}
