import { DocsLayout } from "./DocsLayout";

export default function License() {
  return (
    <DocsLayout>
      <article className="max-w-none">
        {/* Hero */}
        <section className="mb-16">
          <h1 className="text-4xl font-bold tracking-tight mb-4">
            License
          </h1>

          <p className="text-xl text-slate-600 dark:text-slate-300 max-w-3xl">
            Go Bootstrapper is open source software released under the
            permissive MIT License.
          </p>
        </section>

        {/* Summary */}
        <section className="mb-24">
          <h2
            id="what-this-means"
            className="text-2xl font-semibold mb-6"
          >
            What This Means for You
          </h2>

          <div className="grid gap-6 sm:grid-cols-2 max-w-4xl">
            <div className="rounded-xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
              <h3 className="font-semibold mb-3">
                You Are Free To
              </h3>

              <ul className="space-y-2 text-slate-600 dark:text-slate-400">
                <li>Use Go Bootstrapper commercially</li>
                <li>Modify the source code</li>
                <li>Distribute copies or modifications</li>
                <li>Use it privately</li>
                <li>Sublicense the software</li>
              </ul>
            </div>

            <div className="rounded-xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
              <h3 className="font-semibold mb-3">
                You Must
              </h3>

              <ul className="space-y-2 text-slate-600 dark:text-slate-400">
                <li>Include the original copyright notice</li>
                <li>Include the MIT license text</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Generated projects */}
        <section className="mb-24">
          <h2
            id="generated-projects"
            className="text-2xl font-semibold mb-4"
          >
            Generated Projects
          </h2>

          <p className="text-slate-600 dark:text-slate-400 max-w-3xl">
            Projects generated by Go Bootstrapper are <strong>entirely yours</strong>.
            You own the copyright to the generated code and may license it under
            any terms you choose.
          </p>
        </section>

        {/* Warranty */}
        <section className="mb-24">
          <h2
            id="no-warranty"
            className="text-2xl font-semibold mb-4"
          >
            No Warranty
          </h2>

          <p className="text-slate-600 dark:text-slate-400 max-w-3xl">
            Go Bootstrapper is provided “as is”, without warranty of any kind.
            The authors are not liable for any claims, damages, or other liability
            arising from the use of this software.
          </p>
        </section>

        {/* Full license */}
        <section className="mb-24">
          <h2
            id="mit-license"
            className="text-2xl font-semibold mb-6"
          >
            MIT License (Full Text)
          </h2>

          <pre className="rounded-xl border border-slate-200 bg-slate-50 p-6 text-sm overflow-x-auto dark:border-slate-800 dark:bg-slate-900">
{`MIT License

Copyright (c) 2025 Saurav Upadhyay

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`}
          </pre>
        </section>

        {/* Questions */}
        <section className="rounded-2xl border border-slate-200 bg-slate-50 p-8 dark:border-slate-800 dark:bg-slate-900">
          <h2
            id="questions"
            className="text-xl font-semibold mb-2"
          >
            Questions?
          </h2>

          <p className="text-slate-600 dark:text-slate-400">
            If you have questions about licensing or usage, feel free to{" "}
            <a
              href="https://github.com/upsaurav12/bootstrap/issues"
              target="_blank"
              rel="noreferrer"
              className="underline"
            >
              open an issue on GitHub
            </a>.
          </p>
        </section>
      </article>
    </DocsLayout>
  );
}
